name: python-templates
channels:
  - defaults
dependencies:
  - uvicorn
  - black
  - python=3.11
  - fastapi
  - numpy
  - pylint
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - xgboost
  - joblib
  - keras
  - tensorflow
  - pydot
  - statsmodels
  - nltk
  - wordcloud
  - tensorflow-hub
  - opencv
